// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlxk2n7as0FYl4fOwp6djH64z0EL8T6D4',
    appId: '1:308627445496:android:c6fdf210165cdeb53c8d0d',
    messagingSenderId: '308627445496',
    projectId: 'personal-apps-5f1ac',
    databaseURL: 'https://personal-apps-5f1ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personal-apps-5f1ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX-PB8Uol3Trp8Q7A3sbNU1CPbXnyw5dw',
    appId: '1:308627445496:ios:029032009052a7de3c8d0d',
    messagingSenderId: '308627445496',
    projectId: 'personal-apps-5f1ac',
    databaseURL: 'https://personal-apps-5f1ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personal-apps-5f1ac.appspot.com',
    iosClientId: '308627445496-tjokp7gfgvj1iu4j0ooulacsmfeieftr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChat',
  );
}
